### ISSUE TITLE
Training issue.

### ISSUE THREAD

**Issue by narendoraiswamy** [hukenovs/hagrid#3]
Hello,

Thank you for building a large scale dataset for hand gesture recognition. Appreciate the effort. I wanted to request you to please take a look at the training error I am receiving. I am using the ResNet18 model and have modified the paths in the config file accordingly. 

The training starts well but runs into the dataloader issue where it is not able to get the annotations for the training dataloader. I have the error stack in the picture. Any help would be appreciated. 

<img width="1440" alt="Hagrid_error" src="https://user-images.githubusercontent.com/8946594/180662412-5e417854-1335-48a4-81a6-3b871c1d5404.png">

Thank you.

**Comment by anotherhelloworld** [comment]
Hello, @narendoraiswamy 

Can you provide your config you are using? 

Also [this](https://discuss.pytorch.org/t/runtimeerror-received-0-items-of-ancdata/4999/4) thread may help you.

**Comment by nagadit** [comment]
I am closing this issue, but feel free to reopen it if you feel like it has not been resolved.

**Comment by kerem0comert** [comment]
Hello, 
Thanks for the help. 
Let me ask a simple question then, I would very simply like to train a model with the subsample you provide. I could not get it to run by following the README.
At the root of the project I have:
ann_subsample/
subsample/
which I simply downloaded from the README and extracted. From the root of the project, I am running:
```bash
python -m classifier.run --command train --path_to_config classifier/config/default.yaml
```
At this point, I am able to train.

However, I would also like to train n-shot models, where I take n<5 samples per class and train with it. Then I would like to test this model. What would be the procedure for this? Because from what I see, no parameter to set train_test_percentage is provided in default.yaml. Ideally I would like to set train percentage at 1 in training (where the dataset is a subsample of let's say 3 images per gesture class) and then test it on another dataset (perhaps the test that you already provide)
How can I achieve this? Thanks!
