### ISSUE TITLE
Unable to achieve the given mAP when training on the SSDLiteMobileNetV3Large model

### ISSUE THREAD

**Issue by ghhhgfgh** [hukenovs/hagrid#74]
I am using five types(like, fist,palm, peace and no_gesture) to train my own SSDLiteMobileNetV3Large model. My config file is here
[myconfig.txt](https://github.com/user-attachments/files/16377993/myconfig.txt)

And here is how I place my data and annotations. 
![tree](https://github.com/user-attachments/assets/21d34ee9-ff4a-4871-9adc-7ee1c2817d39)

After training for two whole days, my model only achieves a mAP of around 0.4-0.5. Additionally, when I use the trained .pth file with demo.py, it can only detect the fist gesture.

Can someone help me identify what might be going wrong? Thanks!

**Comment by AntonNuzhdin** [comment]
Hello! 

I was unable to reproduce your problem with pretrained SSDLiteMobileNetV3Large, it detects all declared gestures as I see. 
Additionally, I don't see any bugs on our side with the learning process either, most likely you have an error somewhere.

Could you please check it again, since with released HaGRIDv2 dataset?
